### ISSUE TITLE
Date Error

### ISSUE THREAD

**Issue by 2peter3** [nzambello/work-timer#1]
Im getting the following error, do you have any ideas how to fix?

```
react-dom.development.js:86 Warning: Text content did not match. Server: "16:56" Client: "22:56"
    at span
    at p
    at MediaQuery (http://127.0.0.1:4433/build/_shared/chunk-UNACYFJH.js:44723:111)
    at div
    at http://127.0.0.1:4433/build/_shared/chunk-UNACYFJH.js:34174:18
    at TimeElapsed (http://127.0.0.1:4433/build/routes/time-entries-PRF2FVF4.js:58:22)
    at div
    at http://127.0.0.1:4433/build/_shared/chunk-UNACYFJH.js:34174:18
    at div
    at http://127.0.0.1:4433/build/_shared/chunk-UNACYFJH.js:34174:18
    at http://127.0.0.1:4433/build/_shared/chunk-UNACYFJH.js:40227:14
    at section```

**Comment by nzambello** [comment]
@2peter3 this should be fixed now, can you try again?

**Comment by nzambello** [comment]
Closing as this should be fixed and solved. If it's not I'll reopen this
